---
- hosts: all
  become: yes
  tasks:  
  
  - name: install dependencies
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
      update_cache: true
      
  - name: add docker apt key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      
  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      
  - name: Install the package "docker"
    ansible.builtin.apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      
  - name: Check if Docker is started and if no, start Docker
    ansible.builtin.service: 
      name: docker
      state: started
      
  - name: Add the user 'chrisS' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: chrisS
      comment: Christoph Schmid
      uid: 1040
      group: admin
    
  - name: Start a container with a command
    community.docker.docker_container:
      name: hello-world
      image: hello-world
      pull: true     
