---
- hosts: all
  become: yes
  tasks:  
  
  - name: install dependencies
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
      update_cache: true
      
  - name: add docker apt key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      
  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      
  - name: Install the package "docker"
    ansible.builtin.apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      
  - name: Check if Docker is started and if no, start Docker
    ansible.builtin.service: 
      name: docker
      state: started
      
  - name: Test if docker is running
    ansible.builtin.shell: service docker status | grep Active
    register: dockerrun
 
  - name: Output dockerrun command 
    debug:
      var: dockerrun.stdout
            
  - name: Add the user 'chrisS' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: chrisS
      comment: Christoph Schmid
      uid: 1040
      group: admin

  - name: Check if User was added to group
    ansible.builtin.shell: cat /etc/passwd | grep /bin/bash
    register: username

  - name: Show user command
    debug:
      var: username.stdout    
    
  - name: Start a container with a command
    ansible.builtin.shell: docker run hello-world
    register: containername

  - name: Show the docker command
    debug:
      var: containername.stdout
      
  - name: Run a docker command
    ansible.builtin.shell: docker ps -a
    register: result
    
  - name: Show the docker command
    debug: 
      var: result.stdout
