---
- hosts: all
  become: yes
  tasks:  
  
  - name: install dependencies
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
      update_cache: true
      
  - name: add docker apt key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      
  - name: Check if Docker is started and if no, start Docker
    ansible.builtin.service: 
      name: docker
      state: started
    
      
