---
- hosts: all
  tasks:
    azure_rm_virtualmachine:
      validate_certs: false 
  - name: Create test.txt file
    copy:
      content: "This is a test file."
      dest: test.txt
      mode: 0644
      
