---
- hosts: all
  become: yes
  vars:
    user_id: 1040
    container_image: hello-world
  tasks:  
  
  - name: install dependencies
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
      update_cache: true
      
  - name: add docker apt key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      
  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      
  - name: Install the package "docker"
    ansible.builtin.apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      
  - name: Check if Docker is started and if no, start Docker
    ansible.builtin.service: 
      name: docker
      state: started
            
  - name: Add the user 'chrisS' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: chrisS
      comment: Christoph Schmid
      uid: "{{ user_id }}"
      group: admin
      
  - name: Run a docker command
    ansible.builtin.shell: |
      echo ----------------------------------------
      echo >>>>Check if docker is running<<<<
      service docker status | grep Active
      
      echo ----------------------------------------
      echo >>>>Check if User is added<<<<
      cat /etc/passwd | grep "{{ user_id }}"
      
      echo ----------------------------------------
      echo >>>>Run the docker container<<<<
      docker ps -a | head -n 2 | tail -n 1

      echo ----------------------------------------
      echo >>>>Check if docker container is running<<<<
      docker run "{{ container_image }}" | head -n 2 | tail -n 1
      echo ----------------------------------------
      echo >>>>>>>>>>END OF TESTS<<<<<<<<<<<
    register: result

    
  - name: Show the docker commands
    debug: 
      var: result.stdout_lines
