---
- hosts: all
  tasks:
  - name: Set Certs validation on false
    azure_rm_virtualmachine:
      validate_certs: no
  - name: Create test.txt file
    copy:
      content: "This is a test file."
      dest: test.txt
      mode: 0644
      
