---
- hosts: all
  tasks:
  - name: Create test.txt file
    azure_rm_virtualmachine:
       validate_certs: false 
    copy:
      content: "This is a test file."
      dest: test.txt
      mode: 0644
      
